remote_theme: quartzyan/jekyll-theme-minimal


text_skin: forest # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : Sanshi's Blog
description: > # this means to ignore newlines until "Language & timezone"
  Welcome to Sanshi's Blog


## => Language and Timezone
##############################
lang: zh # the language of your site, default as "en"
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : person # "person" (default), "organization"
  name      : Sanshi
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : I am an amazing person.
  email     : 
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : https://www.zhihu.com/people/user_name # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name


kramdown:
  syntax_highlighter: coderay # rouge
